### ISSUE TITLE
Selection of Slots inconsistency in moderator UI

### ISSUE THREAD

**Issue by RalphGanal** [SOFENGG-T1AY1617/S18B-Team-Rofi#55]
Commit: 803d3178440e352a088f6ee257cc0f1644c52dbd

1. Log into moderator page using "rofi_santos@dlsu.edu.ph"
2. Selects slots in any order, quickly

![bug](https://cloud.githubusercontent.com/assets/17705529/21140335/6b610f8a-c172-11e6-83d1-666b6f589bb6.gif)

**Comment by Tobska** [comment]
resolved na dapat to ah?

**Comment by RalphGanal** [comment]
I think I'm still getting a bit of it but it's much much much harder to trigger now. I think this is fine
